version: '3.3'
services:
  iris:
    build:
      context: .
    hostname: from-hl7v2-to-fhir
    ports:
#    - "51773" # 51773 is the superserver default port
    - "1972" # 1972 is the new superserver default port
    - "52776:52773" # 52773 is the webserver/management portal port
    volumes:
    - ./data:/data
    - ./notebook/Notebooks:/Notebooks
    command: 
      # --key /keys/iris.key
      --check-caps false
  fhirhl7v2ui:
    build: ./fhirhl7ui
    depends_on:
      - iris
    ports:
      - "4201:4200"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    command: "npm run proxy"
    volumes:
    - type: bind
      source: ./fhirhl7ui/app/src/app
      target: /home/node/app/src/app
  notebook:
    build: 
      context: notebook
      dockerfile: dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebook/Notebooks:/Notebooks
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/Notebooks"

