### get all patients
GET http://_system:SYS@localhost:52776/fhir/r4/Patient HTTP/1.1
content-type: application/fhir+json
Accept: */*

### get one patient
GET http://_system:SYS@localhost:52776/fhir/r4/Patient/4 HTTP/1.1
content-type: application/fhir+json
Accept: */*

### add one patient with Driver License  
PUT http://_system:SYS@localhost:52776/fhir/r4/Patient/9991 HTTP/1.1
content-type: application/fhir+json
Accept: */*

{
  "resourceType": "Patient",
  "identifier": [
    {
      "use": "official",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "DL",
            "display": "Driver's License"
          }
        ]
      },
      "system": "urn:oid:2.16.840.1.113883.4.3.25",
      "value": "935564323334"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Dupuis",
      "given": [
        "Louis"
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1984-08-30",

  "id": "9991",
  "meta": {
    "lastUpdated": "2024-06-05T16:51:45Z",
    "versionId": "1"
  }
}

### add one patient with Driver License  
PUT http://_system:SYS@localhost:52776/fhir/r4/Patient/9992 HTTP/1.1
content-type: application/fhir+json
Accept: */*

{
  "resourceType": "Patient",
  "identifier": [
    {
      "use": "official",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "DL",
            "display": "Driver's License"
          }
        ]
      },
      "system": "urn:oid:2.16.840.1.113883.4.3.25",
      "value": "635564323334"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Lamarck",
      "given": [
        "Alice"
      ]
    }
  ],
  "gender": "female",
  "birthDate": "2002-04-15",
  "id": "9992",
  "meta": {
    "lastUpdated": "2024-06-05T16:51:45Z",
    "versionId": "1"
  }
}

### add one patient with Driver License  
PUT http://_system:SYS@localhost:52776/fhir/r4/Patient/9993 HTTP/1.1
content-type: application/fhir+json
Accept: */*

{
  "resourceType": "Patient",
  "identifier": [
    {
      "use": "official",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "DL",
            "display": "Driver's License"
          }
        ]
      },
      "system": "urn:oid:2.16.840.1.113883.4.3.25",
      "value": "187788223334"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Potier",
      "given": [
        "Hubert"
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1980-06-18",
  "id": "9993",
  "meta": {
    "lastUpdated": "2024-06-05T16:51:45Z",
    "versionId": "1"
  }
}

### add one patient with Driver License 
POST http://_system:SYS@localhost:52776/fhir/r4/Patient HTTP/1.1
content-type: application/fhir+json
Accept: */*

{
  "resourceType": "Patient",
  "identifier": [
    {
      "use": "official",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "DL",
            "display": "Driver's License"
          }
        ]
      },
      "system": "urn:oid:2.16.840.1.113883.4.3.25",
      "value": "187788223334"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Potier",
      "given": [
        "Hubert"
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1980-06-18"
}

### delete
DELETE http://_system:SYS@localhost:52776/fhir/r4/Patient/2681 HTTP/1.1
content-type: application/fhir+json
Accept: */*